### ISSUE TITLE
Crash for recv sensor_msgs.msg.Image in Android

### ISSUE THREAD

**Issue by aitazhixin** [ros2-java/ros2_java#129] opened 2020-08-24 13:04 UTC
JNI ERROR (app bug): expected jbyte but got value of 184 as argument 1 to void java.lang.Byte.<init>(byte)
 A/zygote64: java_vm_ext.cc:534] JNI DETECTED ERROR IN APPLICATION: bad arguments passed to void java.lang.Byte.<init>(byte) (see above for details)
 A/zygote64: java_vm_ext.cc:534]     from org.ros2.rcljava.interfaces.MessageDefinition org.ros2.rcljava.executors.BaseExecutor.nativeTake(long, java.lang.Class)
 A/zygote64: java_vm_ext.cc:534] "ForkJoinPool.commonPool-worker-1" daemon prio=5 tid=12 Runnable
A/zygote64: java_vm_ext.cc:534]   | group="main" sCount=0 dsCount=0 flags=0 obj=0x12f00540 self=0x7dd76a5400
A/zygote64: java_vm_ext.cc:534]   | sysTid=9523 nice=0 cgrp=default sched=0/0 handle=0x7dc98054f0
A/zygote64: java_vm_ext.cc:534]   | state=R schedstat=( 1536228157 70526463 754 ) utm=141 stm=11 core=5 HZ=100
A/zygote64: java_vm_ext.cc:534]   | stack=0x7dc9703000-0x7dc9705000 stackSize=1037KB
A/zygote64: java_vm_ext.cc:534]   | held mutexes= "mutator lock"(shared held)
A/zygote64: java_vm_ext.cc:534]   native: #00 pc 00000000003ccb5c  /system/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, int, BacktraceMap*, char const*, art::ArtMethod*, void*)+208)

**Comment by jacobperron** [comment] 2020-10-08 23:15
Looks like a duplicate of https://github.com/ros2-java/ros2_java/issues/132, please comment if I'm mistaken.

**Closed by jacobperron** 2020-10-08 23:15 UTC
