### ISSUE TITLE
How Can I set up an Android Build Environment?

### ISSUE THREAD

**Issue by ghost** [ros2-java/ros2_java#61] opened 2019-01-08 01:25 UTC
Sorry if issues are a bad place to bring this up, but I'm having some trouble. I managed to compile ros2_java and have seen "Build Success" at the end of the process. However, what I want to do is use ros2_java in new Android Studio projects. 
By looking at the talker and listener examples, I can see that they have access to ros2_java via jar files that are added via gradle. The problem is, I'm not sure how to get this setup for new projects that I create. 

Any help is appreciated!

**Comment by dulouie** [comment] 2019-02-27 14:50
I've some trouble to setting android build environment too. A more detailed description would be nice.

**Comment by esteve** [comment] 2019-03-08 10:43
@dulouie could you describe in detail what issues you're having? I can try my best to update the documentation, but without more context I don't know what could be improved. Thanks.

**Comment by kuzai** [comment] 2019-03-08 15:05
So a couple months later I've figured a few things out through trial and error. 

The first is that if you use the ament Gradle plugin then you can copy the gradle.properties file from one of the example projects and load it into any project to get up and running. When I was using this approach I simply changed the file paths in gradle.properties to something internal to the project and I had an easy to set up workspace. 

The approach I ended up choosing in the end, however, was to forego ament Gradle entirely and use the ndk to load all of the needed libraries in. After building everything with ament, I used a Unix command to copy all of the libraries to a folder and placed that in my project. I did the same with all header files. Then I linked all of the libraries in cmake with a cpp file that I loaded through Java. This is my preferred method because it's conceptually easier for me to understand and the workflow is more straightforward to me

**Comment by jacobperron** [comment] 2021-11-13 02:32
Closing as duplicate of https://github.com/ros2-java/ros2_java/issues/81

**Closed by jacobperron** 2021-11-13 02:32 UTC
