### ISSUE TITLE
sensor_msgs package is broken

### ISSUE THREAD

**Issue by AviKenz** [ros2-java/ros2_java#121] opened 2020-07-23 10:26 UTC
Hello !
I **CANT** create any object of class `sensor_msgs` (`Image`, `CompressedImage`, `Temperature` tested). 
The app crash when loading type support:
`sensor_msgs_msg__temperature__jni__rosidl_typesupport_c`. 
I tested other packages like `std_msgs `and `geometry_msgs `and they works.

Here is the **Run** output:
![crash error2](https://user-images.githubusercontent.com/35049712/88276547-863adf80-ccdf-11ea-9071-c15af3654f2e.png)

Here is the **logcat** output:
![logcat](https://user-images.githubusercontent.com/35049712/88276606-9eaafa00-ccdf-11ea-9d10-cd6a011bd19e.png)

The package dependency was added into `gradle.properties` under `ament.dependencies` and `ament.exec_dependency_paths_in_workspace`.
any idea on how to fix this ?

Thank you in advance !

**Comment by jacobperron** [comment] 2021-11-13 02:08
Closing because this ticket is quite old. Please try the `main` branch with ROS Galactic and if the issue persists, please open a new ticket with precise steps to reproduce.

**Closed by jacobperron** 2021-11-13 02:08 UTC
